blank_issues_enabled: false
contact_links:
  - name: GitHub Feedback
    url: https://github.com/eu-digital-identity-wallet/eudi-wallet-reference-implementation-roadmap/discussions
    about: Share your feedback.  
